// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="md5_wrap_md5_wrap,hls_ip_2023_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=15734,HLS_SYN_LUT=39682,HLS_VERSION=2023_1}" *)

module md5_wrap (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] text_length;
wire   [63:0] text_input;
wire   [63:0] result;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state2;
reg   [63:0] result_read_reg_267;
reg   [63:0] text_input_read_reg_272;
reg   [31:0] text_length_read_reg_278;
wire   [0:0] icmp_ln127_fu_231_p2;
reg   [0:0] icmp_ln127_reg_320;
reg   [5:0] ctx_data_address0;
reg    ctx_data_ce0;
reg    ctx_data_we0;
reg   [7:0] ctx_data_d0;
wire   [7:0] ctx_data_q0;
reg   [5:0] ctx_data_address1;
reg    ctx_data_ce1;
reg    ctx_data_we1;
wire   [7:0] ctx_data_q1;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_start;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_done;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_idle;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_ready;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWVALID;
wire   [63:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWADDR;
wire   [0:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWID;
wire   [31:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWLEN;
wire   [2:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWSIZE;
wire   [1:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWBURST;
wire   [1:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWLOCK;
wire   [3:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWCACHE;
wire   [2:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWPROT;
wire   [3:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWQOS;
wire   [3:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWREGION;
wire   [0:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWUSER;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_WVALID;
wire   [7:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_WDATA;
wire   [0:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_WSTRB;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_WLAST;
wire   [0:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_WID;
wire   [0:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_WUSER;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARVALID;
wire   [63:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARADDR;
wire   [0:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARID;
wire   [31:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARLEN;
wire   [2:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARSIZE;
wire   [1:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARBURST;
wire   [1:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARLOCK;
wire   [3:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARCACHE;
wire   [2:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARPROT;
wire   [3:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARQOS;
wire   [3:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARREGION;
wire   [0:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARUSER;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_RREADY;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_BREADY;
wire   [5:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_address0;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_ce0;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_we0;
wire   [7:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_d0;
wire   [5:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_address1;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_ce1;
wire   [31:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_3_0_out;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_3_0_out_ap_vld;
wire   [31:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_2_0_out;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_2_0_out_ap_vld;
wire   [31:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_1_0_out;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_1_0_out_ap_vld;
wire   [31:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_0_0_out;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_0_0_out_ap_vld;
wire   [63:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_bitlen_out;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_bitlen_out_ap_vld;
wire   [31:0] grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_p_out;
wire    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_p_out_ap_vld;
wire    grp_md5_final_1_fu_211_ap_start;
wire    grp_md5_final_1_fu_211_ap_done;
wire    grp_md5_final_1_fu_211_ap_idle;
wire    grp_md5_final_1_fu_211_ap_ready;
wire   [5:0] grp_md5_final_1_fu_211_ctx_data_address0;
wire    grp_md5_final_1_fu_211_ctx_data_ce0;
wire    grp_md5_final_1_fu_211_ctx_data_we0;
wire   [7:0] grp_md5_final_1_fu_211_ctx_data_d0;
wire   [5:0] grp_md5_final_1_fu_211_ctx_data_address1;
wire    grp_md5_final_1_fu_211_ctx_data_ce1;
wire    grp_md5_final_1_fu_211_ctx_data_we1;
wire   [7:0] grp_md5_final_1_fu_211_ctx_data_d1;
wire    grp_md5_final_1_fu_211_m_axi_gmem_AWVALID;
wire   [63:0] grp_md5_final_1_fu_211_m_axi_gmem_AWADDR;
wire   [0:0] grp_md5_final_1_fu_211_m_axi_gmem_AWID;
wire   [31:0] grp_md5_final_1_fu_211_m_axi_gmem_AWLEN;
wire   [2:0] grp_md5_final_1_fu_211_m_axi_gmem_AWSIZE;
wire   [1:0] grp_md5_final_1_fu_211_m_axi_gmem_AWBURST;
wire   [1:0] grp_md5_final_1_fu_211_m_axi_gmem_AWLOCK;
wire   [3:0] grp_md5_final_1_fu_211_m_axi_gmem_AWCACHE;
wire   [2:0] grp_md5_final_1_fu_211_m_axi_gmem_AWPROT;
wire   [3:0] grp_md5_final_1_fu_211_m_axi_gmem_AWQOS;
wire   [3:0] grp_md5_final_1_fu_211_m_axi_gmem_AWREGION;
wire   [0:0] grp_md5_final_1_fu_211_m_axi_gmem_AWUSER;
wire    grp_md5_final_1_fu_211_m_axi_gmem_WVALID;
wire   [7:0] grp_md5_final_1_fu_211_m_axi_gmem_WDATA;
wire   [0:0] grp_md5_final_1_fu_211_m_axi_gmem_WSTRB;
wire    grp_md5_final_1_fu_211_m_axi_gmem_WLAST;
wire   [0:0] grp_md5_final_1_fu_211_m_axi_gmem_WID;
wire   [0:0] grp_md5_final_1_fu_211_m_axi_gmem_WUSER;
wire    grp_md5_final_1_fu_211_m_axi_gmem_ARVALID;
wire   [63:0] grp_md5_final_1_fu_211_m_axi_gmem_ARADDR;
wire   [0:0] grp_md5_final_1_fu_211_m_axi_gmem_ARID;
wire   [31:0] grp_md5_final_1_fu_211_m_axi_gmem_ARLEN;
wire   [2:0] grp_md5_final_1_fu_211_m_axi_gmem_ARSIZE;
wire   [1:0] grp_md5_final_1_fu_211_m_axi_gmem_ARBURST;
wire   [1:0] grp_md5_final_1_fu_211_m_axi_gmem_ARLOCK;
wire   [3:0] grp_md5_final_1_fu_211_m_axi_gmem_ARCACHE;
wire   [2:0] grp_md5_final_1_fu_211_m_axi_gmem_ARPROT;
wire   [3:0] grp_md5_final_1_fu_211_m_axi_gmem_ARQOS;
wire   [3:0] grp_md5_final_1_fu_211_m_axi_gmem_ARREGION;
wire   [0:0] grp_md5_final_1_fu_211_m_axi_gmem_ARUSER;
wire    grp_md5_final_1_fu_211_m_axi_gmem_RREADY;
wire    grp_md5_final_1_fu_211_m_axi_gmem_BREADY;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [7:0] gmem_RDATA;
wire   [10:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg   [31:0] ctx_state_3_2_reg_124;
wire    ap_CS_fsm_state12;
reg   [31:0] ctx_state_2_2_reg_136;
reg   [31:0] ctx_state_1_2_reg_148;
reg   [31:0] ctx_state_0_2_reg_160;
reg   [63:0] ctx_bitlen_0_reg_172;
reg   [31:0] ctx_datalen_reg_184;
reg    grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_start_reg;
wire    ap_CS_fsm_state9;
reg   [12:0] ap_NS_fsm;
wire    ap_NS_fsm_state10;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_md5_final_1_fu_211_ap_start_reg;
wire    ap_CS_fsm_state13;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ce_reg;
wire   [31:0] ap_return;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_start_reg = 1'b0;
#0 grp_md5_final_1_fu_211_ap_start_reg = 1'b0;
end

md5_wrap_ctx_data_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
ctx_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(ctx_data_address0),
    .ce0(ctx_data_ce0),
    .we0(ctx_data_we0),
    .d0(ctx_data_d0),
    .q0(ctx_data_q0),
    .address1(ctx_data_address1),
    .ce1(ctx_data_ce1),
    .we1(ctx_data_we1),
    .d1(grp_md5_final_1_fu_211_ctx_data_d1),
    .q1(ctx_data_q1)
);

md5_wrap_md5_wrap_Pipeline_VITIS_LOOP_127_1 grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_start),
    .ap_done(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_done),
    .ap_idle(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_idle),
    .ap_ready(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_ready),
    .m_axi_gmem_AWVALID(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .text_input(text_input_read_reg_272),
    .sext_ln190(text_length_read_reg_278),
    .ctx_data_address0(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_address0),
    .ctx_data_ce0(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_ce0),
    .ctx_data_we0(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_we0),
    .ctx_data_d0(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_d0),
    .ctx_data_q0(ctx_data_q0),
    .ctx_data_address1(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_address1),
    .ctx_data_ce1(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_ce1),
    .ctx_data_q1(ctx_data_q1),
    .ctx_state_3_0_out(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_3_0_out),
    .ctx_state_3_0_out_ap_vld(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_3_0_out_ap_vld),
    .ctx_state_2_0_out(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_2_0_out),
    .ctx_state_2_0_out_ap_vld(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_2_0_out_ap_vld),
    .ctx_state_1_0_out(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_1_0_out),
    .ctx_state_1_0_out_ap_vld(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_1_0_out_ap_vld),
    .ctx_state_0_0_out(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_0_0_out),
    .ctx_state_0_0_out_ap_vld(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_0_0_out_ap_vld),
    .ctx_bitlen_out(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_bitlen_out),
    .ctx_bitlen_out_ap_vld(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_bitlen_out_ap_vld),
    .p_out(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_p_out),
    .p_out_ap_vld(grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_p_out_ap_vld)
);

md5_wrap_md5_final_1 grp_md5_final_1_fu_211(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_md5_final_1_fu_211_ap_start),
    .ap_done(grp_md5_final_1_fu_211_ap_done),
    .ap_idle(grp_md5_final_1_fu_211_ap_idle),
    .ap_ready(grp_md5_final_1_fu_211_ap_ready),
    .ctx_data_address0(grp_md5_final_1_fu_211_ctx_data_address0),
    .ctx_data_ce0(grp_md5_final_1_fu_211_ctx_data_ce0),
    .ctx_data_we0(grp_md5_final_1_fu_211_ctx_data_we0),
    .ctx_data_d0(grp_md5_final_1_fu_211_ctx_data_d0),
    .ctx_data_q0(ctx_data_q0),
    .ctx_data_address1(grp_md5_final_1_fu_211_ctx_data_address1),
    .ctx_data_ce1(grp_md5_final_1_fu_211_ctx_data_ce1),
    .ctx_data_we1(grp_md5_final_1_fu_211_ctx_data_we1),
    .ctx_data_d1(grp_md5_final_1_fu_211_ctx_data_d1),
    .ctx_data_q1(ctx_data_q1),
    .ctx_datalen_val(ctx_datalen_reg_184),
    .p_read(ctx_bitlen_0_reg_172),
    .p_read1(ctx_state_0_2_reg_160),
    .p_read2(ctx_state_1_2_reg_148),
    .p_read3(ctx_state_2_2_reg_136),
    .p_read4(ctx_state_3_2_reg_124),
    .m_axi_gmem_AWVALID(grp_md5_final_1_fu_211_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_md5_final_1_fu_211_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_md5_final_1_fu_211_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_md5_final_1_fu_211_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_md5_final_1_fu_211_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_md5_final_1_fu_211_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_md5_final_1_fu_211_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_md5_final_1_fu_211_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_md5_final_1_fu_211_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_md5_final_1_fu_211_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_md5_final_1_fu_211_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_md5_final_1_fu_211_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_md5_final_1_fu_211_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_md5_final_1_fu_211_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_md5_final_1_fu_211_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_md5_final_1_fu_211_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_md5_final_1_fu_211_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_md5_final_1_fu_211_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_md5_final_1_fu_211_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(1'b0),
    .m_axi_gmem_ARADDR(grp_md5_final_1_fu_211_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_md5_final_1_fu_211_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_md5_final_1_fu_211_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_md5_final_1_fu_211_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_md5_final_1_fu_211_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_md5_final_1_fu_211_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_md5_final_1_fu_211_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_md5_final_1_fu_211_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_md5_final_1_fu_211_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_md5_final_1_fu_211_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_md5_final_1_fu_211_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(1'b0),
    .m_axi_gmem_RREADY(grp_md5_final_1_fu_211_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(8'd0),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(11'd0),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_md5_final_1_fu_211_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .hash(result_read_reg_267)
);

md5_wrap_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(32'd1),
    .text_length(text_length)
);

md5_wrap_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .text_input(text_input),
    .result(result)
);

md5_wrap_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 11 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARLEN(gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(grp_md5_final_1_fu_211_m_axi_gmem_AWADDR),
    .I_AWLEN(grp_md5_final_1_fu_211_m_axi_gmem_AWLEN),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(grp_md5_final_1_fu_211_m_axi_gmem_WDATA),
    .I_WSTRB(grp_md5_final_1_fu_211_m_axi_gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_md5_final_1_fu_211_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_md5_final_1_fu_211_ap_start_reg <= 1'b1;
        end else if ((grp_md5_final_1_fu_211_ap_ready == 1'b1)) begin
            grp_md5_final_1_fu_211_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state10) & (1'b1 == ap_CS_fsm_state9))) begin
            grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_start_reg <= 1'b1;
        end else if ((grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_ready == 1'b1)) begin
            grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln127_fu_231_p2 == 1'd1))) begin
        ctx_bitlen_0_reg_172 <= 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln127_reg_320 == 1'd0))) begin
        ctx_bitlen_0_reg_172 <= grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_bitlen_out;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln127_fu_231_p2 == 1'd1))) begin
        ctx_datalen_reg_184 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln127_reg_320 == 1'd0))) begin
        ctx_datalen_reg_184 <= grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_p_out;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln127_fu_231_p2 == 1'd1))) begin
        ctx_state_0_2_reg_160 <= 32'd1732584193;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln127_reg_320 == 1'd0))) begin
        ctx_state_0_2_reg_160 <= grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_0_0_out;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln127_fu_231_p2 == 1'd1))) begin
        ctx_state_1_2_reg_148 <= 32'd4023233417;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln127_reg_320 == 1'd0))) begin
        ctx_state_1_2_reg_148 <= grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_1_0_out;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln127_fu_231_p2 == 1'd1))) begin
        ctx_state_2_2_reg_136 <= 32'd2562383102;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln127_reg_320 == 1'd0))) begin
        ctx_state_2_2_reg_136 <= grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_2_0_out;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln127_fu_231_p2 == 1'd1))) begin
        ctx_state_3_2_reg_124 <= 32'd271733878;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln127_reg_320 == 1'd0))) begin
        ctx_state_3_2_reg_124 <= grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_state_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln127_reg_320 <= icmp_ln127_fu_231_p2;
        result_read_reg_267 <= result;
        text_input_read_reg_272 <= text_input;
        text_length_read_reg_278 <= text_length;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_md5_final_1_fu_211_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (grp_md5_final_1_fu_211_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (grp_md5_final_1_fu_211_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ctx_data_address0 = grp_md5_final_1_fu_211_ctx_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        ctx_data_address0 = grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_address0;
    end else begin
        ctx_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ctx_data_address1 = grp_md5_final_1_fu_211_ctx_data_address1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        ctx_data_address1 = grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_address1;
    end else begin
        ctx_data_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ctx_data_ce0 = grp_md5_final_1_fu_211_ctx_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        ctx_data_ce0 = grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_ce0;
    end else begin
        ctx_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ctx_data_ce1 = grp_md5_final_1_fu_211_ctx_data_ce1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        ctx_data_ce1 = grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_ce1;
    end else begin
        ctx_data_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ctx_data_d0 = grp_md5_final_1_fu_211_ctx_data_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        ctx_data_d0 = grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_d0;
    end else begin
        ctx_data_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ctx_data_we0 = grp_md5_final_1_fu_211_ctx_data_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        ctx_data_we0 = grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ctx_data_we0;
    end else begin
        ctx_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ctx_data_we1 = grp_md5_final_1_fu_211_ctx_data_we1;
    end else begin
        ctx_data_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_ARADDR = text_input_read_reg_272;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARADDR = grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_ARLEN = text_length_read_reg_278;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARLEN = grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARVALID = grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_AWVALID = grp_md5_final_1_fu_211_m_axi_gmem_AWVALID;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_BREADY = grp_md5_final_1_fu_211_m_axi_gmem_BREADY;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_RREADY = grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_WVALID = grp_md5_final_1_fu_211_m_axi_gmem_WVALID;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln127_fu_231_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln127_fu_231_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (grp_md5_final_1_fu_211_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state10 = ap_NS_fsm[32'd9];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_md5_final_1_fu_211_ap_start = grp_md5_final_1_fu_211_ap_start_reg;

assign grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_start = grp_md5_wrap_Pipeline_VITIS_LOOP_127_1_fu_196_ap_start_reg;

assign icmp_ln127_fu_231_p2 = ((text_length == 32'd0) ? 1'b1 : 1'b0);

endmodule //md5_wrap
